### PR TITLE
fix: Resizing webpage seems to cause issues with <Model> #369

### LINKED ISSUE #369: Resizing webpage seems to cause issues with <Model>
Image

### PR DESCRIPTION
**Pull request by walton007**
fix #369

### CODE REVIEW

File: react/src/spatial-react-components/Model3D/useDetectLayoutDomUpdated.ts [hunk 1]
```diff
@@ -3,6 +3,17 @@ import { useRef, useEffect } from 'react'
 export function useDetectLayoutDomUpdated(onDomUpdated: () => void) {
   const ref = useRef<HTMLDivElement>(null)
 
+  // detect window resize
+  useEffect(() => {
+    const handleResize = () => {
+      onDomUpdated()
+    }
+    window.addEventListener('resize', handleResize)
```
Comment (mzvast) [inline react/src/spatial-react-components/Model3D/useDetectLayoutDomUpdated.ts:11]: Will remove this listener cause not react to container size change?
I remember this was related to another bug.

Comment (TrevorDev) [reply react/src/spatial-react-components/Model3D/useDetectLayoutDomUpdated.ts:11]: I am worried that resize is a subset of the changes we are not detecting. I thought we already added a resize handler somewhere else. Hope we dont add a bunch of one off event listeners being added everywhere doing similar things.

Comment (TrevorDev) [reply react/src/spatial-react-components/Model3D/useDetectLayoutDomUpdated.ts:11]: This change looks OKish to me but if theres a better fix please do that instead. Will leave this to @mzvast to approve.

Comment (walton007) [reply react/src/spatial-react-components/Model3D/useDetectLayoutDomUpdated.ts:11]: Maybe a resize hook can be used to reduce duplicate code
