### PR TITLE
fix(react): stabilize head style sync for spatial windows

### LINKED ISSUE #1033: Fix unstable head style sync in spatial windows and guard non-string className
## Overview
This issue tracks two related stability problems that were observed while using spatial windows (SpatialDiv / attachments) in the React SDK.

### Symptoms
When the host page `<head>` changes rapidly (e.g. Vite HMR or frequent dynamic `<style>` injections), the child window created for SpatialDiv/attachments may:
- accumulate duplicated synced stylesheet `<link>` elements over time, or
- have existing synced stylesheet `<link>` elements removed/replaced during rapid updates.

### Expected
- Synced stylesheet `<link>` elements in the child window remain stable (not replaced) when the host’s stylesheet list is unchanged.
- No duplicated synced stylesheet links are appended.

### Actual
- Duplicated stylesheet links can appear, or synced links can be replaced during rapid host `<head>` mutations.

### How to Reproduce
1. Render a SpatialDiv (`<div enable-xr>`) or an attachment portal.
2. Continuously mutate the host `<head>` (e.g. add/remove a `<style>` tag at a high frequency).
3. Observe the child window `<head>` for `link[rel=\"stylesheet\"][data-webspatial-sync=\"1\"]` changes.

### Symptoms
`replaceToSpatialPrimitiveType` previously assumed `props.className` is a string and called `.split(' ')`. Some third-party libraries (e.g. `NavLink` from react-router) may pass `className` as a function, which can cause a runtime exception.

### Expected
- No runtime error when a component provides `className` as a function or other non-string value.

### Actual
- A non-string `className` can trigger an exception during the JSX transform path.

### How to Reproduce
1. Use a component that accepts `className` as a function (e.g. `NavLink`) in a context where the JSX transform checks `className`.
2. The previous `.split(' ')` call on a non-string value can throw.

## Fix
- Use the shared `useSyncHeadStyles` hook for ongoing head synchronization.
- Make `syncParentHeadToChild` idempotent and concurrency-safe to avoid duplicate injection and to drop stale in-flight syncs.
- Add a type guard in `replaceToSpatialPrimitiveType` so it only splits `className` when it is a string.

## Verification
- Test-server probe: open `/#/head-style-sync` and click `Run host head stress`. Expect the probe to stay `PASS` without link duplication.
- Confirm a `NavLink` (or equivalent) passing `className` as a function no longer causes a runtime error.

## References
- PR: https://github.com/webspatial/webspatial-sdk/pull/1032

### PR DESCRIPTION
**Pull request by walton007**
Fixes #1033

## Summary
Stabilize head style synchronization for spatial windows (SpatialDiv/attachments) and harden the JSX transform against non-string `className` values.

## Changes
- Use the shared `useSyncHeadStyles` hook for ongoing head updates in both the SpatialDiv (Spatialized2DElement) path and the attachment window path.
- Make `syncParentHeadToChild` idempotent and concurrency-safe to avoid re-adding the same stylesheet links and to drop stale in-flight syncs.
- Guard `replaceToSpatialPrimitiveType` so it only calls `.split(' ')` when `props.className` is a string, avoiding runtime errors when third-party libs (e.g. `NavLink`) pass a function.
- Add a test-server probe page to stress host `<head>` mutations and validate that synced stylesheet links remain stable (not replaced/duplicated).
- Add a Changeset for `@webspatial/react-sdk`.

## Verification
- Run `pnpm -C apps/test-server dev` and open `/#/head-style-sync`.
- Click `Run host head stress`.
- Expect the probe to stay `PASS`, with the baseline stylesheet link still connected and the synced link count not increasing.
- Render a `NavLink` (or any component that provides `className` as a function) in the app; confirm no runtime exception is thrown by the JSX transform.

## Notes
- CI uses `pnpm install --frozen-lockfile`, so the lockfile is kept in sync with `packages/react/package.json` changes.

### CODE REVIEW

File: apps/test-server/src/pages/head-style-sync/index.tsx [hunk 1]
```diff
@@ -0,0 +1,252 @@
+import React from 'react'
```
Comment (khufu-dev) [inline apps/test-server/src/pages/head-style-sync/index.tsx]:
```suggestion
import {useRef, useCallback, useState} from 'react'
```

File: apps/test-server/src/pages/head-style-sync/index.tsx [hunk 2]
```diff
@@ -0,0 +1,252 @@
...
+import { enableDebugTool } from '@webspatial/react-sdk'
+
+enableDebugTool()
+
+function HeadSyncProbe() {
+  const rootRef = React.useRef<HTMLDivElement | null>(null)
```
Comment (khufu-dev) [inline apps/test-server/src/pages/head-style-sync/index.tsx]:
```suggestion
  const rootRef = useRef<HTMLDivElement | null>(null)
```

File: packages/react/src/reality/components/AttachmentEntity.tsx [hunk 3]
```diff
@@ -1,14 +1,17 @@
 import React, { useEffect, useRef, useState } from 'react'
+
```
Comment (khufu-dev) [inline packages/react/src/reality/components/AttachmentEntity.tsx]:
```suggestion
```

File: packages/react/src/reality/components/AttachmentEntity.tsx [hunk 4]
```diff
@@ -1,14 +1,17 @@
...
 import { Attachment } from '@webspatial/core-sdk'
+
```
Comment (khufu-dev) [inline packages/react/src/reality/components/AttachmentEntity.tsx:3]:
```suggestion
```

File: packages/react/src/spatialized-container/Spatialized2DElementContainer.tsx [hunk 5]
```diff
@@ -75,26 +78,17 @@ function useSyncDocumentTitle(
...
 function SpatializedContent<P extends ElementType>(
   props: SpatializedContentProps<SpatializedElementRef, P>,
 ) {
   const { spatializedElement, ...restProps } = props
   const spatialized2DElement = spatializedElement as Spatialized2DElement
-  const windowProxy = spatialized2DElement.windowProxy
+  const { windowProxy } = spatialized2DElement
 
-  useSyncHeaderStyle(windowProxy)
+  useSyncHeadStyles(windowProxy, {
```
Comment (khufu-dev) [inline packages/react/src/spatialized-container/Spatialized2DElementContainer.tsx:88]: Good name change

File: packages/react/src/utils/useSyncHeadStyles.ts [hunk 6]
```diff
@@ -0,0 +1,63 @@
+import { useEffect } from 'react'
```
Comment (khufu-dev) [inline packages/react/src/utils/useSyncHeadStyles.ts:1]: Rename the file to `useSyncHeadStyles.ts` to be consistent with React hook file naming

File: packages/react/src/utils/useSyncHeadStyles.ts [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+interface Options {
+  delayMs?: number
+  subtree?: boolean
+  immediate?: boolean
+}
+
+function defaultShouldSync(mutations?: MutationRecord[] | null) {
+  if (!Array.isArray(mutations) || mutations.length === 0) return false
+  for (const mutation of mutations) {
+    const nodes: Node[] = [
```
Comment (khufu-dev) [inline packages/react/src/utils/useSyncHeadStyles.ts:13]:
```suggestion
    const nodes = [
```

File: packages/react/src/utils/useSyncHeadStyles.ts [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+      ...Array.from(mutation.addedNodes),
+      ...Array.from(mutation.removedNodes),
+    ]
+    for (const node of nodes) {
+      if (!(node instanceof Element)) continue
+      const tag = node.tagName
+      if (tag === 'STYLE') return true
+      if (tag === 'LINK') {
```
Comment (khufu-dev) [inline packages/react/src/utils/useSyncHeadStyles.ts:21]: According to [W3C specs](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element) the link tag can be in the head or body. Do we support both?

File: packages/react/src/utils/use-sync-head-styles.ts [hunk 9]
```diff
@@ -0,0 +1,63 @@
+import { useEffect } from 'react'
+
+import { syncParentHeadToChild } from './windowStyleSync'
+
+interface Options {
+  delayMs?: number
```
Comment (khufu-dev) [inline packages/react/src/utils/use-sync-head-styles.ts]: Should we omit this property so we can standardize the timeout.

File: packages/react/src/utils/windowStyleSync.ts [hunk 10]
```diff
@@ -1,36 +1,44 @@
...
-    // ~1/50 loads, if the same url is loaded very quickly in a window and a child window,
-    // the second load request never is fired resulting in css not to be applied.
-    // Workaround this by making the css stylesheet request unique
-    n.href += '?uniqueURL=' + Math.random()
-    n.onerror = function (error) {
-      console.error('Failed to load style link', (n as HTMLLinkElement).href)
-      resolve(false)
+    const { href } = n
+    const sep = href.includes('?') ? '&' : '?'
+    n.href = `${href}${sep}uniqueURL=${Math.random()}`
```
Comment (khufu-dev) [inline packages/react/src/utils/windowStyleSync.ts]:
```suggestion
    n.href = `${href}${sep}uniqueURL=${crypto.randomUUID()}`
```

File: packages/react/src/utils/windowStyleSync.ts [hunk 11]
```diff
@@ -1,36 +1,44 @@
...
+    let finished = false
+    const finish = (ok: boolean) => {
+      if (finished) return
+      finished = true
+      resolve(ok)
+    }
+
+    n.onerror = () => {
+      finish(false)
+    }
```
Comment (khufu-dev) [inline packages/react/src/utils/windowStyleSync.ts]:
```suggestion
    n.onerror = () =>  finish(false)
```

File: packages/react/src/utils/windowStyleSync.ts [hunk 12]
```diff
@@ -1,36 +1,44 @@
 export function asyncLoadStyleToChildWindow(
   childWindow: WindowProxy,
   n: HTMLLinkElement,
```
Comment (khufu-dev) [inline packages/react/src/utils/windowStyleSync.ts]: `n` is not descriptive enough.
```suggestion
  link: HTMLLinkElement,
```

File: packages/react/src/utils/windowStyleSync.ts [hunk 13]
```diff
@@ -1,36 +1,44 @@
...
-    n.onload = () => resolve(true)
 
-    // need to wait for some time to make sure the style is loaded
-    // otherwise, the style may not be applied
     setTimeout(() => {
+      if (!isCurrent()) {
+        finish(false)
+        return
+      }
       childWindow.document.head.appendChild(n)
```
Comment (khufu-dev) [inline packages/react/src/utils/windowStyleSync.ts]: Will this throw an error if childWindow is closed before the timeout completes?

File: packages/react/src/utils/windowStyleSync.ts [hunk 14]
```diff
@@ -1,36 +1,44 @@
...
+        n.parentNode?.removeChild(n)
+        finish(false)
+        return
+      }
+      finish(true)
     }
-    n.onload = () => resolve(true)
 
-    // need to wait for some time to make sure the style is loaded
-    // otherwise, the style may not be applied
```
Comment (khufu-dev) [inline packages/react/src/utils/windowStyleSync.ts:18]: Keep the comment to justify the timeout.

File: packages/react/src/spatialized-container/Spatialized2DElementContainer.tsx (hunk 5 above)
Comment (walton007) [reply packages/react/src/spatialized-container/Spatialized2DElementContainer.tsx:88]: What's your suggest name?

File: packages/react/src/utils/use-sync-head-styles.ts (hunk 9 above)
Comment (walton007) [reply packages/react/src/utils/use-sync-head-styles.ts]: OK

File: packages/react/src/utils/useSyncHeadStyles.ts (hunk 7 above)
Comment (walton007) [reply packages/react/src/utils/useSyncHeadStyles.ts:13]: I hope keep the type declaration

File: packages/react/src/utils/useSyncHeadStyles.ts (hunk 8 above)
Comment (walton007) [reply packages/react/src/utils/useSyncHeadStyles.ts:21]: No. We support head only now.

File: packages/react/src/utils/windowStyleSync.ts (hunk 12 above)
Comment (walton007) [reply packages/react/src/utils/windowStyleSync.ts]: OK

File: packages/react/src/utils/windowStyleSync.ts (hunk 10 above)
Comment (walton007) [reply packages/react/src/utils/windowStyleSync.ts]: Prefer Math.random, which is faster.

File: packages/react/src/utils/windowStyleSync.ts (hunk 11 above)
Comment (walton007) [reply packages/react/src/utils/windowStyleSync.ts]: Can keep this coding style, which might help adding console info

File: packages/react/src/utils/windowStyleSync.ts (hunk 13 above)
Comment (walton007) [reply packages/react/src/utils/windowStyleSync.ts]: I think isCurrent function is used to avoid this

File: packages/react/src/utils/windowStyleSync.ts (hunk 14 above)
Comment (walton007) [reply packages/react/src/utils/windowStyleSync.ts:18]: Agree. Keep the comment

File: packages/react/src/spatialized-container/Spatialized2DElementContainer.tsx (hunk 5 above)
Comment (walton007) [reply packages/react/src/spatialized-container/Spatialized2DElementContainer.tsx:88]: We can have another PR when you have a better name candidate

Comment (khufu-dev) [reply packages/react/src/spatialized-container/Spatialized2DElementContainer.tsx:88]: Sorry, I meant to communicate that this is a good name change 👍
