### PR TITLE
Scroll in nested spatialdiv

### LINKED ISSUE #439: page scroll is not working when in nested spatialdiv
**Repoduce branch:** https://github.com/webspatial/webspatial-sdk/tree/scroll-in-nested-spatialdiv

When there's no nested spatialdiv, scroll can work normally

Image

But when there's nested spatialdiv, scroll **can't** work

Image

### PR DESCRIPTION
**Pull request by walton007**
fix #439

### CODE REVIEW

File: builder/visionOS/web-spatial/libs/webView/manifest.swift [hunk 1]
```diff
@@ -5,7 +5,7 @@ var pwaManager = PWAManager()
 
 struct PWAManager: Codable {
     var isLocal: Bool = false
-    var start_url: String = "http://localhost:5173/"
+    var start_url: String = "http://localhost:5173"
```
Comment (TrevorDev) [inline builder/visionOS/web-spatial/libs/webView/manifest.swift]: why?

File: builder/visionOS/web-spatial/libs/SpatialWindowComponent.swift [hunk 2]
```diff
@@ -233,6 +234,21 @@ class SpatialWindowComponent: SpatialComponent {
         return webViewNative!.webViewHolder.appleWebView!.scrollView.isScrollEnabled
     }
 
+    func findNearestScrollEnabledSpatialWindowComponent() -> SpatialWindowComponent? {
```
Comment (TrevorDev) [inline builder/visionOS/web-spatial/libs/SpatialWindowComponent.swift:244]: add comment for expected behavior

File: builder/visionOS/web-spatial/views/SpatialWebViewUI.swift [hunk 3]
```diff
@@ -78,25 +78,30 @@ struct SpatialWebViewUI: View {
                                                 DragGesture()
                                                     .onChanged { gesture in
                                                         let scrollEnabled = view.isScrollEnabled()
-                                                        if !scrollEnabled, wv.isScrollEnabled() {
-                                                            if !view.dragStarted {
-                                                                view.dragStarted = true
-                                                                view.dragStart = (gesture.translation.height)
+                                                        if !scrollEnabled {
```
Comment (TrevorDev) [inline builder/visionOS/web-spatial/views/SpatialWebViewUI.swift:81]: add comment for expected behavior based on this change

File: package.json [hunk 4]
```diff
@@ -33,8 +33,7 @@
     ],
     "*": [
       "node -e \"const fs = require('fs'); process.argv.slice(1).forEach(file => { if (fs.existsSync(file)) { const size = fs.statSync(file).size; if (size >= 1048576) { console.error(`Error: ${file} is 1MB or larger`); process.exit(1); }}})\"",
-      "node -e \"const fs=require('fs'),f=process.argv[1],c=fs.readFileSync(f,'utf8').split('\\n').filter(l=>/[\\u4E00-\\u9FFF]/.test(l)); if(c.length) { console.error('Non english characters detected:\\n' + c.join('\\n')); process.exit(1); }\"",
-      "node devScripts/sensitiveWords.js"
+      "node -e \"const fs=require('fs'),f=process.argv[1],c=fs.readFileSync(f,'utf8').split('\\n').filter(l=>/[\\u4E00-\\u9FFF]/.test(l)); if(c.length) { console.error('Non english characters detected:\\n' + c.join('\\n')); process.exit(1); }\""
```
Comment (TrevorDev) [inline package.json:36]: why is this modified?

File: builder/visionOS/web-spatial/libs/webView/manifest.swift (hunk 1 above)
Comment (walton007) [reply builder/visionOS/web-spatial/libs/webView/manifest.swift]: it's a mistake, I'll revert it.

File: package.json (hunk 4 above)
Comment (walton007) [reply package.json:36]: I remove the sensitive words check.

File: builder/visionOS/web-spatial/views/SpatialWebViewUI.swift (hunk 3 above)
Comment (walton007) [reply builder/visionOS/web-spatial/views/SpatialWebViewUI.swift:81]: comment added

File: builder/visionOS/web-spatial/libs/SpatialWindowComponent.swift (hunk 2 above)
Comment (walton007) [reply builder/visionOS/web-spatial/libs/SpatialWindowComponent.swift:244]: comment added
