### PR TITLE
Fix spatialwindowcomponent setstyle

### LINKED ISSUE #282: Using image in spatialDiv causes page to go black
```
  <SpatialDiv spatialStyle={{
        position: { z: 50 },
        cornerRadius: 10,
      }}>
        test
        <img src=" https://picsum.photos/200/300" />
      </SpatialDiv>
```

Image

### PR DESCRIPTION
**Pull request by walton007**
fix #282

### CODE REVIEW

File: testServer/src/docsWebsite/examples/reactDomElement.tsx [hunk 1]
```diff
@@ -1,67 +1,19 @@
...
-    <div className="m-10">
-      <input
-        type="range"
-        step="0.005"
-        min={-Math.PI * 2}
-        max={Math.PI * 2}
-        className="mt-10 m-10 w-60 h-3 bg-gray-200 rounded-lg appearance-none cursor-pointer range-lg dark:bg-gray-700"
-        onChange={async e => {
-          setRotation(Number(e.target.value))
+    <div className="flex flex-col items-center w-full">
```
Comment (TrevorDev) [inline testServer/src/docsWebsite/examples/reactDomElement.tsx]: can you revert this file, this was just repro code overwriting this file.

File: builder/visionOS/web-spatial/libs/Utils/CommandManager.swift [hunk 2]
```diff
@@ -492,9 +492,6 @@ class CommandManager {
             }
 
             if let backgroundMaterial: BackgroundMaterial = data.update?.style?.backgroundMaterial {
-                if target.isLoading {
```
Comment (TrevorDev) [inline builder/visionOS/web-spatial/libs/Utils/CommandManager.swift:495]: Can you summarize what the cause of this issue was? Some of this isLoading logic was here on purpose to avoid changing the current styles while the new webpage hasnt yet been displayed.

File: testServer/src/docsWebsite/examples/reactDomElement.tsx (hunk 1 above)
Comment (walton007) [reply testServer/src/docsWebsite/examples/reactDomElement.tsx]: OK. I'll revert the file

File: builder/visionOS/web-spatial/libs/Utils/CommandManager.swift (hunk 2 above)
Comment (walton007) [reply builder/visionOS/web-spatial/libs/Utils/CommandManager.swift:495]: I have added some comment here: 
https://github.com/webspatial/webspatial-sdk/issues/282

Comment (walton007) [reply builder/visionOS/web-spatial/libs/Utils/CommandManager.swift:495]: **setStyle** is called by SpatialDiv and window global style.
They should have different behavior,  maybe we should provide different api

Comment (walton007) [reply builder/visionOS/web-spatial/libs/Utils/CommandManager.swift:495]: following process steps leads to the background material bug:
1. load entry html in root WindowComponent's webview
2. parse global css and call  setStyle(glassMaterial)
  - root WindowComponent's loadingStyles.backgroundMaterial is set to glassMaterial
3. parse spatialdiv
  - portalInstance will create a WindowComponent, let's called it SubWindowComponent
  -  portalInstance set SubWindowComponent's backgroundMaterial to None
  **- code in line 495 will loadingStyles.backgroundMaterial to None (This is not the expected behavior)**
 4. finish load entry html
   - didFinishLoadPage is called and loadingStyles.backgroundMaterial will be used to set the page's background material **which have wrong value 'None'**

Comment (TrevorDev) [reply builder/visionOS/web-spatial/libs/Utils/CommandManager.swift:495]: Discussed a bit:

basePage (MaterialType: None == css background #00000000 == white, opacity = true )
    spatialDiv (MaterialType: transparent == css background #00000000 == transparent, opacity=false)

basePage defaults to None
spatialDIv defaults to Transparent
